# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-12 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumedrop', '0003_auto_20160311_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_year',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='wpi_username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
