# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumedrop', '0011_auto_20160320_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.FileField(default='', max_length=3000, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.FileField(upload_to=''),
        ),
    ]
