# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import resumedrop.models


class Migration(migrations.Migration):

    dependencies = [
        ('resumedrop', '0013_auto_20160321_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.FileField(upload_to=resumedrop.models.content_file_name),
        ),
    ]
